---
- name: Add a new domain to EPG binding
  aci_epg_to_domain:
    host: "{{ inventory_hostname }}"
    username: "{{ aci_username }}"
    password: "{{ password }}"
    validate_certs: no
    tenant: "{{ item.tenant }}"
    ap: "{{ item.ap }}"
    epg: "{{ item.name }}"
    domain: "{{ item.vmmdomain }}"
    domain_type: "{{ item.domaintype }}"
    vm_provider: "{{ item.vmprovider }}"
    state: present
  loop: "{{ epg }}"
