---
- name: Deploy infrastructure
  hosts: aci
  gather_facts: False
  vars_prompt:
    - name: "aci_username"
      prompt: "Please introduce ACI username"
      private: no
    - name: "aci_password"
      prompt: "Please introduce ACI password"
  roles:
    - aci_tenant
    - aci_vrf
    - aci_bd
    - aci_bd_subnet
    - aci_anp
    - aci_epg
    - aci_epg_to_contract
    - aci_epg_to_domain
