---

- name: Add a new tenant
  aci_tenant:
   host: "{{ inventory_hostname }}"
   username: "{{ aci_username }}"
   password: "{{ aci_password }}"
   validate_certs: no
   tenant: "{{ item.name }}"
   description: "{{ item.description }}"
   state: present
  delegate_to: localhost
  loop: "{{ tenants }}"

