---

epg_contracts:
  - tenant: CBRE
    ap: APP-1
    epg: WEB-TIER
    name: APP1-WEB-TO-APP
    type: consumer

  - tenant: CBRE
    ap: APP-1
    epg: APP-TIER
    name: APP1-WEB-TO-APP
    type: provider

  - tenant: CBRE
    ap: APP-1
    epg: APP-TIER
    name: APP1-APP-TO-DB
    type: consumer

  - tenant: CBRE
    ap: APP-1
    epg: DB-TIER
    name: APP1-APP-TO-DB
    type: provider


l3out_contracts:
  - tenant: CBRE
    ap: APP-1
    epg: WEB-TIER
    name: APP1-OUTSIDE-TO-WEB
    type: provider
