---
- name: Add a new bd
  aci_bd:
    host: "{{ inventory_hostname }}"
    username: "{{ aci_username }}"
    password: "{{ aci_password }}"
    validate_certs: no
    tenant: "{{ item.tenant }}"
    bd: "{{ item.name }}"
    description: "{{ item.description }}"
    vrf: "{{ item.vrf }}"
    state: present
  loop: "{{ bds }}"

