---
- name: Add a new contract for EPG to EPG Communication
  aci_epg_to_contract:
    host: apic1
    username: "{{ aci_username }}"
    password: "{{ password }}"
    validate_certs: no
    tenant: "{{ item.tenant }}"
    ap: "{{ item.ap }}"
    epg: "{{ item.epg }}"
    contract: "{{ item.name }}"
    contract_type: "{{ item.type }}"
    state: present
  with_items: "{{ epg_contracts }}"

- name: Add a new contract for EPG to L3OUT Communication
  aci_epg_to_contract:
    host: apic1
    username: "{{ aci_username }}"
    password: "{{ password }}"
    validate_certs: no
    tenant: "{{ item.tenant }}"
    ap: "{{ item.ap }}"
    epg: "{{ item.epg }}"
    contract: "{{ item.name }}"
    contract_type: "{{ item.type }}"
    state: present
  with_items: "{{ l3out_contracts }}"

