---
- name: Add a new ANP to Tenant
  aci_ap:
   host: "{{ inventory_hostname }}"
   username: "{{ aci_username }}"
   password: "{{ aci_password }}"
   validate_certs: no
   tenant: "{{ item.tenant }}"
   ap: "{{ item.name }}"
   description: "{{ item.description }}"
   state: present
  loop: "{{ anps }}"
