---

- name: Add a new epg
  aci_epg:
    host: "{{ inventory_hostname }}"
    username: "{{ aci_username }}"
    password: "{{ password }}"
    validate_certs: no
    tenant: "{{ item.tenant }}"
    ap: "{{ item.ap }}"
    epg: "{{ item.name }}"
    description: "{{ item.description }}"
    bd: "{{ item.bd }}"
    state: present
  loop: "{{ epg }}"

